CREATE TABLE comments
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text     VARCHAR(255),
    video_id BIGINT,
    user_id  BIGINT,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE videos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    filename    VARCHAR(255),
    user_id     BIGINT,
    CONSTRAINT pk_videos PRIMARY KEY (id)
);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_VIDEO FOREIGN KEY (video_id) REFERENCES videos (id);

ALTER TABLE videos
    ADD CONSTRAINT FK_VIDEOS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);