ALTER TABLE videos
ADD COLUMN views BIGINT NOT NULL DEFAULT 0;

ALTER TABLE videos
ADD COLUMN like_count BIGINT NOT NULL  DEFAULT 0;

ALTER TABLE videos
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;